### ISSUE TITLE
getObservationsForSeries doesn't work 

### ISSUE THREAD

**Issue by AndyLL** [pastorsj/node-fred#106]
even the example provided here<https://pastorsj.github.io/node-fred-api/#get-observations-for-series > returns the following:

Error {
    error_code: 400,
    error_message: 'Bad Request.  Value of units is not one of: cap, cca, cch, ch1, chg, lin, log, pc1, pca, pch.'
}

**Comment by pastorsj** [comment]
@AndyLL Thanks for letting me know. I will look at it this weekend and get a patch out asap.

**Comment by AndyLL** [comment]
Sorry for the tongue, I was quite upset about my work earlier today. Have a
nice weekend.

**Comment by pastorsj** [comment]
Issue got closed early by the PR getting merged in, but I need to deploy it and check before confirming the issue is fixed.

**Comment by pastorsj** [comment]
@AndyLL This should be fixed in version 2.1.8. Please let me know if that works for you and I will close the issue.

**Comment by AndyLL** [comment]
It's fixed, great work XD
