### ISSUE TITLE
`Observations` property on series data gives static type checking error

### ISSUE THREAD

**Issue by sjunel** [pastorsj/node-fred#110]
Hi @pastorsj!

I've pulled series data using the `getObservationsForSeries` method and I'm trying to use the `filter` method on data accessed via the `observations` property. A static type checking error is blocking me from transpiling.

The code I'm using is:
```
const series = await fred.series.getObservationsForSeries('SP500');

let data = series.observations.filter((obj: any) => {
  // test implementation
});
```
And the error I'm getting is:
```
src/app.ts:31:36 - error TS2339: Property 'filter' does not exist on type 'ObservationSet'.

31     let data = series.observations.filter((obj: any) => {
                                      ~~~~~~
```
I double checked the wrapper documentation, and it does says that the returned JSON's `observations` property has a value of an array of objects, so it's odd that I'm not able to use an array method. 

Would appreciate it if you looked into this! Thanks in advance.

**Comment by pastorsj** [comment]
Hi @sjunel, this should be fixed. Version 2.1.10 is published. It looks like the typings file was slightly off. Please let me know if anything else seems off and I can fix it.

**Comment by sjunel** [comment]
Thank you, Sam!
