### ISSUE TITLE
Builders hatch onto previously built params

### ISSUE THREAD

**Issue by Dynogic** [pastorsj/node-fred#38]
Hi, thanks for the library! It's a very pleasant read.

One issue I've run into, however. If I execute ```fred.series.getObservationsForSeries('SP500', { units: 'lin', frequency: 'm' })``` and then ```fred.series.getObservationsForSeries('SP500', { units: 'lin' })``` again, the latter call returns a ```monthly``` frequency, but the expected is the default frequency, ```daily```.

Temporary fix is to always explicitly define ```frequency```.

**Comment by pastorsj** [comment]
Thanks for letting me know, I will take a look at fixing this weekend.

**Comment by Dynogic** [comment]
Cheers!

Additionally, seems like the URL builder does not reset when these API methods are re-called. You end up getting stack-up of attributes. E.g. if I call SP500, then PERMIT1, a URL like ```series/observations?series_id=SP500&units=lin&frequency=d&series_id=PERMIT1&units=lin&frequency=m``` is crafted for PERMIT1. Fred will return PERMIT1's observations. However, queries can eventually get so large, the query just doesn't go through. 😄 I'm currently creating an entirely new ```Fred``` object on a re-query -- this currently feels like a _hack_ and expensive.

**Comment by pastorsj** [comment]
Apologies for getting sidetracked on this issue. I have pushed a new npm package (2.1.5) that should fix this issue.

**Comment by Dynogic** [comment]
Thanks!
