### ISSUE TITLE
Cannot Find Module error when trying to use Node-Fred

### ISSUE THREAD

**Issue by JasonSooter** [pastorsj/node-fred#8]
I'm not able to use this package as I get a Cannot Find Module error. I first received the error when trying to run a basic js file with node. I get the same error when trying to use the package with RunKit. Also, trying to include it via unpkg.com get's the same error. Any ideas?

https://unpkg.com/node-fred@2.0.8
<img width="570" alt="https___unpkg_com_node-fred_2_0_8" src="https://user-images.githubusercontent.com/7215306/27519432-73b42f70-59b9-11e7-89f7-9d97e5969ac1.png">

https://runkit.com/jasonsooter/basic-node-fred-script
<img width="1171" alt="untitled___runkit" src="https://user-images.githubusercontent.com/7215306/27519446-98b2e7a8-59b9-11e7-9b93-4c1f37798908.png">

**Comment by pastorsj** [comment]
Thanks for letting me know. I will take a look at it as soon as possible.

**Comment by pastorsj** [comment]
So I just checked and it looks like when I install node-feed into a simple example, the lib/ directory does not exist. I attempted to build the library before deploying to npm, and it seems to not be doing that. I will try and fix it soon.

**Comment by pastorsj** [comment]
@JasonSooter I believe the issue has been fixed in the latest version 2.0.9. See https://unpkg.com/node-fred@2.0.9 Please confirm this before I close the issue. Thanks!

**Comment by JasonSooter** [comment]
@pastorsj Yep, That did the trick! I appreciate the quick response and helpful tool. Have a Great Day! Thanks! 
-Jason
