### ISSUE TITLE
Throws a window error on loading

### ISSUE THREAD

**Issue by mchennupati** [pastorsj/node-fred#83]
Hi @pastorjs,

This looks like a very useful library. However, I couldn't get it to work :)

I tried to use it on codesandbox and also here https://npm.runkit.com/node-fred. I get the following error. Did I miss something ? (import doesn't yet appear to work on node.js, so I used require.)
Thanks !
_**ReferenceError: window is not defined
Fix: Use global instead of window.
RunKit is a node environment, so window and other browser features won’t exist. If you’re just trying to access the global object, you can simply use global instead.**_

**Comment by pastorsj** [comment]
Thanks for letting me know. I wonder whether a change in node versions might have caused some issues. I will look into this.

**Comment by mchennupati** [comment]
Cool, thanks for that. I like how you designed the wrapper, with builder as the core and adding each data category on top.  Very readable.  My guess is that it's a webpack issue. 

https://github.com/webpack/webpack/issues/7112

**Comment by pastorsj** [comment]
@mchennupati Thanks for reporting this issue. It seemed like webpack was updated and I had to target node in the webpack configuration file. See this [issue](https://github.com/axios/axios/issues/244#issuecomment-325895075).

**Comment by pastorsj** [comment]
I tested this using the npm runkit and it seems to be functioning again. Please reach out if anything else comes up. Closing this issue.
